
package prolab2_3;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author BerkayEfe
 */
public class GirisGUI extends javax.swing.JFrame {

    private VeriTabanı veriTabanı;
    private String adSoyad;
    private String email;
    private String dogumTarihi;
    private String parola;
    private String[] kullaniciVerileri;
    private String id;

    public GirisGUI() {

        veriTabanı = new VeriTabanı();
       
        initComponents();
        pencereyiOrtala();
        setIconImage(Toolkit.getDefaultToolkit().getImage(
                getClass().getResource("/filmResimleri/frameLogo.png")));
        

    }

    private void pencereyiOrtala() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kayıtOlButton = new javax.swing.JButton();
        parolaPasswordField = new javax.swing.JPasswordField();
        girisButton = new javax.swing.JButton();
        emailTextField = new javax.swing.JTextField();
        parolaLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NETFLIX");
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(680, 444));
        setPreferredSize(new java.awt.Dimension(680, 444));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));
        jPanel1.setForeground(new java.awt.Color(23, 23, 23));
        jPanel1.setMinimumSize(new java.awt.Dimension(670, 423));

        kayıtOlButton.setText("Kayıt  ol ");
        kayıtOlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtOlButtonActionPerformed(evt);
            }
        });

        girisButton.setBackground(new java.awt.Color(23, 23, 23));
        girisButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        girisButton.setForeground(new java.awt.Color(255, 255, 255));
        girisButton.setText("Giriş");
        girisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisButtonActionPerformed(evt);
            }
        });

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        parolaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        parolaLabel.setForeground(new java.awt.Color(255, 255, 255));
        parolaLabel.setText("Parola:");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email :");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filmResimleri/logo.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hesabınız mı yok ?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(emailLabel)
                        .addGap(4, 4, 4)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(parolaLabel)
                        .addGap(6, 6, 6)
                        .addComponent(parolaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(girisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kayıtOlButton)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(emailLabel))
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(parolaLabel))
                    .addComponent(parolaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(girisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kayıtOlButton))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void girisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisButtonActionPerformed
        email = emailTextField.getText(); // arayuzden verileri cekiyoruz.
        parola = new String(parolaPasswordField.getPassword());
        kullaniciVerileri = veriTabanı.girisYap(email, parola);
        id = kullaniciVerileri[0];
        adSoyad = kullaniciVerileri[1];
        dogumTarihi = kullaniciVerileri[2];
        if (id != null) {
            new KullaniciAnaSayfa(id, adSoyad, email, dogumTarihi);

            dispose();
            OturumKontolcusu.kullaniciEmailYaz(email);
        }
    }//GEN-LAST:event_girisButtonActionPerformed

    private void kayıtOlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtOlButtonActionPerformed
        new KayitGUI();

        dispose(); // bu nesne yok ediliyor
    }//GEN-LAST:event_kayıtOlButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        oturumKontrolluBasla();
       //oturumKontrolsuzBasla();

    }
    private static void oturumKontrolluBasla(){
        
        String email = OturumKontolcusu.kullaniciEmailOku();

        // eger oturum bilgisi yoksa giris icin arayuz olusturulur.
        if (email.equals("-")) {
            oturumKontrolsuzBasla();
        }
        else{
            VeriTabanı geciciVeriTabanı = new VeriTabanı();
            String[] kullaniciBilgileri = geciciVeriTabanı.kullaniciVerileriniGetir(email);
            String id = kullaniciBilgileri[0];
            String adSoyad = kullaniciBilgileri[1];
            String dogumTarihi = kullaniciBilgileri[2];
            new KullaniciAnaSayfa(id, adSoyad, email, dogumTarihi);
        }
    }
    private static void oturumKontrolsuzBasla(){
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new GirisGUI().setVisible(true);
                }
            });

    }

    public static void gorunurOl() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton girisButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kayıtOlButton;
    private javax.swing.JLabel parolaLabel;
    private javax.swing.JPasswordField parolaPasswordField;
    // End of variables declaration//GEN-END:variables
}
