package prolab2_3;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.regex.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author BerkayEfe
 */
public class KayitGUI extends javax.swing.JFrame {

    private String email;
    private String adSoyad;
    private String parola;
    private String dogumTarihi;
    private VeriTabanı veriTabanı;
    private UyarıMesajı uyarıMesajı = new UyarıMesajı();
    private BilgiMesajı bilgiMesajı = new BilgiMesajı();

    public KayitGUI() {
        veriTabanı = new VeriTabanı();

        initComponents();
        pencereyiOrtala();
        comboBoxKurulum();
        setVisible(true);
        verilerinDogrulugunuTestEt();
        filmPanel.setVisible(false);
        filmScrollPane.setVisible(false);
         setIconImage(Toolkit.getDefaultToolkit().getImage(
                 getClass().getResource("/filmResimleri/frameLogo.png")));

    }
    protected void finalize(){
        GirisGUI.gorunurOl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anaPanel = new javax.swing.JPanel();
        baslikLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        parolaLabel = new javax.swing.JLabel();
        dogumTarihiLabel = new javax.swing.JLabel();
        adSoyadLabel = new javax.swing.JLabel();
        sifreTekrarLabel = new javax.swing.JLabel();
        adSoyadTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        kayıtOlButton = new javax.swing.JButton();
        parolaPasswordField = new javax.swing.JPasswordField();
        parolaTekrarPasswordField = new javax.swing.JPasswordField();
        emailIsaretLabel = new javax.swing.JLabel();
        adSoyadIsaretLabel = new javax.swing.JLabel();
        dogumTarihiIseretLabel = new javax.swing.JLabel();
        parolaUyumLabel = new javax.swing.JLabel();
        gunComboBox = new javax.swing.JComboBox<>();
        ayComboBox = new javax.swing.JComboBox<>();
        yilComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        girisSayfasinaDonButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        filmTuruIsaretLabel3 = new javax.swing.JLabel();
        filmTuru1ComboBox = new javax.swing.JComboBox<>();
        filmTuru2ComboBox = new javax.swing.JComboBox<>();
        filmTuru3ComboBox = new javax.swing.JComboBox<>();
        filmTuruIsaretLabel1 = new javax.swing.JLabel();
        filmTuruIsaretLabel2 = new javax.swing.JLabel();
        filmScrollPane = new javax.swing.JScrollPane();
        filmPanel = new javax.swing.JPanel();
        titleLabel2 = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        titleLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NETFLIX");
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setPreferredSize(new java.awt.Dimension(1280, 700));
        getContentPane().setLayout(null);

        anaPanel.setBackground(new java.awt.Color(23, 23, 23));
        anaPanel.setMinimumSize(new java.awt.Dimension(1280, 700));
        anaPanel.setPreferredSize(new java.awt.Dimension(1280, 700));

        baslikLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        baslikLabel.setForeground(new java.awt.Color(255, 255, 255));
        baslikLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baslikLabel.setText("KULLANICI KAYIT SAYFASI");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("Email          :");

        parolaLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        parolaLabel.setForeground(new java.awt.Color(255, 255, 255));
        parolaLabel.setText("Parola         :");

        dogumTarihiLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dogumTarihiLabel.setForeground(new java.awt.Color(255, 255, 255));
        dogumTarihiLabel.setText("Doğum tarihi :");

        adSoyadLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adSoyadLabel.setForeground(new java.awt.Color(255, 255, 255));
        adSoyadLabel.setText("Ad ve Soyad :");

        sifreTekrarLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sifreTekrarLabel.setForeground(new java.awt.Color(255, 255, 255));
        sifreTekrarLabel.setText("Parola tekrar :");

        kayıtOlButton.setBackground(new java.awt.Color(55, 55, 55));
        kayıtOlButton.setForeground(new java.awt.Color(255, 255, 255));
        kayıtOlButton.setText("Kayıt Ol");
        kayıtOlButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        kayıtOlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayıtOlButtonActionPerformed(evt);
            }
        });

        emailIsaretLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailIsaretLabel.setText("ok");
        emailIsaretLabel.setPreferredSize(new java.awt.Dimension(25, 25));

        adSoyadIsaretLabel.setForeground(new java.awt.Color(255, 255, 255));
        adSoyadIsaretLabel.setText("ok");
        adSoyadIsaretLabel.setPreferredSize(new java.awt.Dimension(25, 25));

        dogumTarihiIseretLabel.setForeground(new java.awt.Color(255, 255, 255));
        dogumTarihiIseretLabel.setText("ok");
        dogumTarihiIseretLabel.setPreferredSize(new java.awt.Dimension(25, 25));

        parolaUyumLabel.setForeground(new java.awt.Color(255, 255, 255));
        parolaUyumLabel.setText("uym");

        gunComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        yilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("/");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("/");

        girisSayfasinaDonButton.setBackground(new java.awt.Color(55, 55, 55));
        girisSayfasinaDonButton.setForeground(new java.awt.Color(255, 255, 255));
        girisSayfasinaDonButton.setText("<-  Giriş Sayfası");
        girisSayfasinaDonButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        girisSayfasinaDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisSayfasinaDonButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filmResimleri/logo.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("3.Film Türü  :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1.Film Türü  :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2.Film Türü  :");

        filmTuruIsaretLabel3.setForeground(new java.awt.Color(255, 255, 255));
        filmTuruIsaretLabel3.setText("jLabel7");

        filmTuru1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filmTuru2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filmTuru3ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filmTuruIsaretLabel1.setForeground(new java.awt.Color(255, 255, 255));
        filmTuruIsaretLabel1.setText("jLabel7");

        filmTuruIsaretLabel2.setForeground(new java.awt.Color(255, 255, 255));
        filmTuruIsaretLabel2.setText("jLabel7");

        javax.swing.GroupLayout anaPanelLayout = new javax.swing.GroupLayout(anaPanel);
        anaPanel.setLayout(anaPanelLayout);
        anaPanelLayout.setHorizontalGroup(
            anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaPanelLayout.createSequentialGroup()
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(girisSayfasinaDonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(baslikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(adSoyadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adSoyadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adSoyadIsaretLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailIsaretLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(dogumTarihiLabel)
                        .addGap(16, 16, 16)
                        .addComponent(gunComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(ayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(yilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(dogumTarihiIseretLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filmTuru1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filmTuruIsaretLabel1))
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filmTuru2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filmTuru3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filmTuruIsaretLabel2)
                            .addComponent(filmTuruIsaretLabel3))
                        .addGap(90, 90, 90)
                        .addComponent(kayıtOlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parolaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifreTekrarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(anaPanelLayout.createSequentialGroup()
                                .addComponent(parolaTekrarPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(parolaUyumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(parolaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(270, 270, 270))
        );
        anaPanelLayout.setVerticalGroup(
            anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(girisSayfasinaDonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(baslikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adSoyadLabel)
                    .addComponent(adSoyadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adSoyadIsaretLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIsaretLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parolaLabel)
                    .addComponent(parolaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parolaUyumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sifreTekrarLabel)
                            .addComponent(parolaTekrarPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dogumTarihiLabel)
                    .addComponent(gunComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dogumTarihiIseretLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(filmTuru1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filmTuruIsaretLabel1))
                .addGap(10, 10, 10)
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(filmTuru2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filmTuruIsaretLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(filmTuru3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filmTuruIsaretLabel3)))
                    .addGroup(anaPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(kayıtOlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        getContentPane().add(anaPanel);
        anaPanel.setBounds(0, 0, 1280, 700);

        filmScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        filmScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        filmScrollPane.setAutoscrolls(true);
        filmScrollPane.setMinimumSize(new java.awt.Dimension(1280, 1000));
        filmScrollPane.setPreferredSize(new java.awt.Dimension(1280, 1000));

        filmPanel.setBackground(new java.awt.Color(55, 55, 55));
        filmPanel.setMinimumSize(new java.awt.Dimension(1010, 1000));
        filmPanel.setPreferredSize(new java.awt.Dimension(1010, 1000));

        titleLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel2.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel2.setText("1.Kategoride en çok ");

        titleLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.setText("1.Kategoride en çok");

        titleLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel3.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel3.setText("1.Kategoride en çok ");

        jButton1.setBackground(new java.awt.Color(55, 55, 55));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Giriş Yap");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filmPanelLayout = new javax.swing.GroupLayout(filmPanel);
        filmPanel.setLayout(filmPanelLayout);
        filmPanelLayout.setHorizontalGroup(
            filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmPanelLayout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(titleLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        filmPanelLayout.setVerticalGroup(
            filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filmPanelLayout.createSequentialGroup()
                .addGroup(filmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filmPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(filmPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(234, 234, 234)
                .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265)
                .addComponent(titleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        filmScrollPane.setViewportView(filmPanel);

        getContentPane().add(filmScrollPane);
        filmScrollPane.setBounds(0, 0, 1270, 685);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void pencereyiOrtala() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
    }
    private void kayıtOlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayıtOlButtonActionPerformed
        adSoyad = adSoyadTextField.getText();
        email = emailTextField.getText();
        parola = new String(parolaPasswordField.getPassword());
        dogumTarihi = "";
        dogumTarihi += gunComboBox.getSelectedItem();
        dogumTarihi += "/";
        dogumTarihi += ayComboBox.getSelectedItem();
        dogumTarihi += "/";
        dogumTarihi += yilComboBox.getSelectedItem();
        //System.out.println(dogumTarihi);
        
        if(veriTabanı.emailKayitliMi(email)){
            uyarıMesajı.mesajVer("Kullanici zaten sisteme kayıtlı", "Kullanıcı mevcut");
        }
        else {
            veriTabanı.kullaniciEkle(adSoyad, parola, email, dogumTarihi);
            bilgiMesajı.mesajVer("Kullanıcı başarıyla kayıt edildi", "BAŞARILI KAYIT");
             turlereGoreEnCokIzlenen2FilmiFilmPanelineEkle();
        }
       
    }//GEN-LAST:event_kayıtOlButtonActionPerformed
    public void panelinBoyutunuArttir(JPanel panel, int w, int h) {

        Dimension dimension = new Dimension(w, h);
        panel.setPreferredSize(dimension);
        panel.setSize(dimension);
    }
    private void turlereGoreEnCokIzlenen2FilmiFilmPanelineEkle() {
        
        String secilenTur1 = (String) filmTuru1ComboBox.getSelectedItem();
        String secilenTur2 = (String) filmTuru2ComboBox.getSelectedItem();
        String secilenTur3 = (String) filmTuru3ComboBox.getSelectedItem();
        String secilenTurlerArray[] = new String[3];
        secilenTurlerArray[0] = secilenTur1;
        secilenTurlerArray[1] = secilenTur2;
        secilenTurlerArray[2] = secilenTur3;
        
        
        int x = 450;
        int y = 50;
        ArrayList<ArrayList<String>> programlar;
        for (String secilenTur : secilenTurlerArray) {
            programlar = veriTabanı.turIsmineGoreEnCokPuanAlanIkiFilmiGetir(secilenTur);
          
            for (ArrayList<String> program : programlar) {
                String id = program.get(0);
                String ad = program.get(1);
                String puan = program.get(2);

                paneleProgramEkle(filmPanel, id, ad, puan, x, y);
                //System.out.println(id);
                x += 250;
            }
            x =450;
            y+=300;
            if(y+300>filmPanel.getHeight()){
                panelinBoyutunuArttir(filmPanel, filmPanel.getWidth(), y+400);
            }
        }
        

        //veriTabanı.turIsmineGoreEnCokPuanAlanIkiFilmiGetir(secilenTur2);
        //veriTabanı.turIsmineGoreEnCokPuanAlanIkiFilmiGetir(secilenTur3);
        titleLabel1.setText(secilenTur1 + " türünde en çok puan alan 2 film :");
        titleLabel2.setText(secilenTur2 + " türünde en çok puan alan 2 film :");
        titleLabel3.setText(secilenTur3 + " türünde en çok puan alan 2 film :");
        anaPanel.setVisible(false);
        filmPanel.setVisible(true);
        filmScrollPane.setVisible(true);
        
    }

    private void paneleProgramEkle(JPanel anaJpanel, String programID, String ad,
            String puan, int x, int y) {

        String path = "/filmResimleri/" + programID + ".jpg";
        //System.out.println(path);
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        JButton button = new JButton(icon);
        JLabel label = new JLabel();
        label.setText(ad);
        label.setForeground(Color.white);
        label.setBounds(x, y + 200, 140, 20);
        button.setBounds(x, y, 140, 190);
        anaJpanel.add(button);
        anaJpanel.add(label);
        repaint();

        //button.seti
    }

    private void girisSayfasinaDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisSayfasinaDonButtonActionPerformed
        new GirisGUI().gorunurOl();

        dispose();
    }//GEN-LAST:event_girisSayfasinaDonButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        GirisGUI.gorunurOl();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void verilerinDogrulugunuTestEt() {
        // kullanicidan alinan verilerin dogrulugu test ediliyor bu thread ile saglaniyor.
        Thread test = new Thread(new Runnable() {
            @Override
            public void run() {
                int sayac = 0;
                String adSoyad;
                String email;
                String parola;
                String parolaTekrar;
                String dogumTarihi;
                String filmTur1;
                String filmTur2;
                String filmTur3;
                String tarihRegex = "^[0-3]?[0-9]\\/[0-9]?[0-9]\\/\\d*$";
                String emailRegex = "^[A-Za-z0-9+_.-]+@(.+)$";
                Pattern desen = Pattern.compile(emailRegex);
                Pattern tarihDesen = Pattern.compile(tarihRegex);
                Matcher matcher;
                Matcher tarihMatcher;
                while (true) {
                    sayac = 0;
                    dogumTarihi = "";
                    adSoyad = adSoyadTextField.getText();
                    email = emailTextField.getText();
                    parola = new String(parolaPasswordField.getPassword());
                    parolaTekrar = new String(parolaTekrarPasswordField.getPassword());
                    dogumTarihi += (String) gunComboBox.getSelectedItem();
                    dogumTarihi += "/";
                    dogumTarihi += ayComboBox.getSelectedItem();
                    dogumTarihi += "/";
                    dogumTarihi += yilComboBox.getSelectedItem();
                    filmTur1 = (String) filmTuru1ComboBox.getSelectedItem();
                    filmTur2 = (String) filmTuru2ComboBox.getSelectedItem();
                    filmTur3 = (String) filmTuru3ComboBox.getSelectedItem();
                    // dogum tarihi icin eslesmeye bakiliyor.
                    tarihMatcher = tarihDesen.matcher(dogumTarihi);
                    matcher = desen.matcher(email);
                    if (adSoyad.length() > 0) {
                        tikIsaretiAta(adSoyadIsaretLabel);
                        sayac++;
                    } else {
                        carpiIsaretiAta(adSoyadIsaretLabel);
                        sayac--;
                    }
                    if (matcher.matches()) { //eger eslesme oluyorsa
                        tikIsaretiAta(emailIsaretLabel);
                        sayac++;
                    } else {
                        carpiIsaretiAta(emailIsaretLabel);
                        sayac--;
                    }
                    if (parola.equals(parolaTekrar) && parola.length() > 0) {

                        tikIsaretiAta(parolaUyumLabel);
                        sayac++;
                    } else {
                        parolaUyumLabel.setText("Şifreler uyumsuz");
                        parolaUyumLabel.setForeground(Color.red);
                        sayac--;
                    }
                    if (tarihMatcher.matches()) {
                        tikIsaretiAta(dogumTarihiIseretLabel);
                        sayac++;
                    } else {
                        carpiIsaretiAta(dogumTarihiIseretLabel);
                        sayac--;
                    }
                    if (!filmTur1.equals("-------------")) {
                        tikIsaretiAta(filmTuruIsaretLabel1);
                        sayac++;
                    } else {
                        carpiIsaretiAta(filmTuruIsaretLabel1);
                        sayac--;
                    }
                    if (!filmTur2.equals("-------------")) {
                        tikIsaretiAta(filmTuruIsaretLabel2);
                        sayac++;
                    } else {
                        carpiIsaretiAta(filmTuruIsaretLabel2);
                        sayac--;
                    }
                    if (!filmTur3.equals("-------------")) {
                        tikIsaretiAta(filmTuruIsaretLabel3);
                        sayac++;
                    } else {
                        carpiIsaretiAta(filmTuruIsaretLabel3);
                        sayac--;
                    }
                    if (sayac == 7) {
                        kayıtOlButton.setVisible(true);
                    } else {
                        kayıtOlButton.setVisible(false);
                    }

                    try {
                        Thread.sleep(700); // 700 ms beklenecek.
                    } catch (InterruptedException ex) {
                        System.out.println("Thread kesintiye uğradı");
                    }

                }

            }
        });

        test.start(); // thread baslatiliyor.

    }

    private void comboBoxKurulum() {
        String[] gunler = new String[32];
        String[] aylar = new String[13];
        String[] yillar = new String[201];
        String[] filmTur1 = new String[14];
        String[] filmTur2 = new String[14];
        String[] filmTur3 = new String[14];
        ArrayList<String> programIsimleri = veriTabanı.turTablosundanTurIsimleriniGetir();
        filmTur1[0] = "-------------";
        filmTur2[0] = "-------------";
        filmTur3[0] = "-------------";
        for (int i = 1; i < 14; i++) {
            filmTur1[i] = programIsimleri.get(i - 1);
            filmTur2[i] = programIsimleri.get(i - 1);
            filmTur3[i] = programIsimleri.get(i - 1);
        }
        gunler[0] = "--";
        aylar[0] = "--";
        yillar[0] = "--";
        int i;
        for (i = 1; i < 32; i++) {// gunler ataniyor.
            gunler[i] = Integer.toString(i);
        }
        for (i = 1; i < 13; i++) {
            aylar[i] = Integer.toString(i);
        }
        for (i = 1; i < 201; i++) {
            yillar[i] = Integer.toString(i + 1900);
        }
        final DefaultComboBoxModel gunModel = new DefaultComboBoxModel(gunler);
        final DefaultComboBoxModel ayModel = new DefaultComboBoxModel(aylar);
        final DefaultComboBoxModel yilModel = new DefaultComboBoxModel(yillar);
        final DefaultComboBoxModel turIsimBoxModel1 = new DefaultComboBoxModel(filmTur1);
        final DefaultComboBoxModel turIsimBoxModel2 = new DefaultComboBoxModel(filmTur2);
        final DefaultComboBoxModel turIsimBoxModel3 = new DefaultComboBoxModel(filmTur3);
        gunComboBox.setModel(gunModel); // model comboBox a ataniyor.
        ayComboBox.setModel(ayModel); // model comboBox a ataniyor.
        yilComboBox.setModel(yilModel); // model comboBox a ataniyor.
        filmTuru1ComboBox.setModel(turIsimBoxModel1);
        filmTuru2ComboBox.setModel(turIsimBoxModel2);
        filmTuru3ComboBox.setModel(turIsimBoxModel3);

    }

    private void tikIsaretiAta(javax.swing.JLabel label) {
        label.setText("\u2713");
        label.setForeground(Color.white);
    }

    private void carpiIsaretiAta(javax.swing.JLabel label) {
        label.setText("\u274C");
        label.setForeground(Color.red);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adSoyadIsaretLabel;
    private javax.swing.JLabel adSoyadLabel;
    private javax.swing.JTextField adSoyadTextField;
    private javax.swing.JPanel anaPanel;
    private javax.swing.JComboBox<String> ayComboBox;
    private javax.swing.JLabel baslikLabel;
    private javax.swing.JLabel dogumTarihiIseretLabel;
    private javax.swing.JLabel dogumTarihiLabel;
    private javax.swing.JLabel emailIsaretLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel filmPanel;
    private javax.swing.JScrollPane filmScrollPane;
    private javax.swing.JComboBox<String> filmTuru1ComboBox;
    private javax.swing.JComboBox<String> filmTuru2ComboBox;
    private javax.swing.JComboBox<String> filmTuru3ComboBox;
    private javax.swing.JLabel filmTuruIsaretLabel1;
    private javax.swing.JLabel filmTuruIsaretLabel2;
    private javax.swing.JLabel filmTuruIsaretLabel3;
    private javax.swing.JButton girisSayfasinaDonButton;
    private javax.swing.JComboBox<String> gunComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton kayıtOlButton;
    private javax.swing.JLabel parolaLabel;
    private javax.swing.JPasswordField parolaPasswordField;
    private javax.swing.JPasswordField parolaTekrarPasswordField;
    private javax.swing.JLabel parolaUyumLabel;
    private javax.swing.JLabel sifreTekrarLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    private javax.swing.JComboBox<String> yilComboBox;
    // End of variables declaration//GEN-END:variables
}
