package prolab2_3;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author BerkayEfe
 */
public class KullaniciAnaSayfa extends javax.swing.JFrame {

    private String id;
    private String adSoyad;
    private String email;
    private String dogumTarihi;
    private int kalinanBolum = 1;
    private int gloabalProgramID;
    private int verilenPuan;
    private int izledigimSure;
    private int programinBolumSayisi;
    private String programAdi;
    private String programinTipi;
    private String programinUzunlugu;
    private VeriTabanı veriTabanı;
    private ArrayList<JCheckBox> turCheckBoxs;
    private ArrayList<String> turIsimleriArrayList;
    private Thread sayacThread;
    private BilgiMesajı bilgiMesajı;
    private int sureKontrol;

    public KullaniciAnaSayfa(String id, String adSoyad, String email, String dogumTarihi) {
        this.id = id;
        this.adSoyad = adSoyad;
        this.email = email;
        this.dogumTarihi = dogumTarihi;
        bilgiMesajı = new BilgiMesajı();
        turIsimleriArrayList = new ArrayList<>();
        turCheckBoxs = new ArrayList<>();
        veriTabanı = new VeriTabanı();
        initComponents();
        turCheckBoxs.add(jCheckBox1);
        turCheckBoxs.add(jCheckBox2);
        turCheckBoxs.add(jCheckBox3);
        turCheckBoxs.add(jCheckBox4);
        turCheckBoxs.add(jCheckBox5);
        turCheckBoxs.add(jCheckBox6);
        turCheckBoxs.add(jCheckBox7);
        turCheckBoxs.add(jCheckBox8);
        turCheckBoxs.add(jCheckBox9);
        turCheckBoxs.add(jCheckBox10);
        turCheckBoxs.add(jCheckBox11);
        turCheckBoxs.add(jCheckBox12);
        turCheckBoxs.add(jCheckBox13);
        setIconImage(Toolkit.getDefaultToolkit().getImage(
                getClass().getResource("/filmResimleri/frameLogo.png")));
        setVisible(true);
        pencereyiOrtala();
        anaPaneliGorunurYap();
        kullanicininIzledigiFilmeleriAnaPaneleEkle();
        tumProgramlariPaneleEkle("");
        //System.out.println("id : " + id + " adSoyad :"+adSoyad + " email: "+ email + " dogumTarihi: "+ dogumTarihi  );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kullaniciBilgileriPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        cikisYapButton = new javax.swing.JButton();
        kullaniciIsimLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        anaEkranBaslikPanel = new javax.swing.JPanel();
        turAramaButton = new javax.swing.JButton();
        aramaTextField = new javax.swing.JTextField();
        araButton = new javax.swing.JButton();
        anaEkranaDonButton = new javax.swing.JButton();
        kullaniciBilgileriButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        anaEkranScrollPane = new javax.swing.JScrollPane();
        anaEkranPanel = new javax.swing.JPanel();
        izlemeyeDevamEtLabel = new javax.swing.JLabel();
        ismeGoreAramaSonucScrollPane = new javax.swing.JScrollPane();
        ismeGoreAramaSonucPanel = new javax.swing.JPanel();
        filmlerBaslikLabel = new javax.swing.JLabel();
        dizilerVeTVShowBaslikLabel2 = new javax.swing.JLabel();
        eslesenFilmYokLabel = new javax.swing.JLabel();
        eslesenDiziYokLabel = new javax.swing.JLabel();
        tureGoreAramaSonucScrollPane = new javax.swing.JScrollPane();
        tureGoreAramaPanel = new javax.swing.JPanel();
        sonucYokLabel = new javax.swing.JLabel();
        kategoriSecLabel = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        tureGoreAramaTextField = new javax.swing.JTextField();
        tureGoreAraButton = new javax.swing.JButton();
        bulunanDiziFilmlerLabel = new javax.swing.JLabel();
        programIzlemePanel = new javax.swing.JPanel();
        izlenenDakikaLabel = new javax.swing.JLabel();
        programIzlemeGeriButton = new javax.swing.JButton();
        ilerGeriSarSlider = new javax.swing.JSlider();
        programBasligiLabel = new javax.swing.JLabel();
        programSuresiLabel = new javax.swing.JLabel();
        programIzlemeDurdurmaButton = new javax.swing.JButton();
        puanVerButton = new javax.swing.JButton();
        oncekiBolumButton = new javax.swing.JButton();
        sonrakiBolumButton2 = new javax.swing.JButton();
        tumProgramlarScrollPane = new javax.swing.JScrollPane();
        tumProgramlarSonucPanel = new javax.swing.JPanel();
        filmlerBaslikLabel1 = new javax.swing.JLabel();
        dizilerVeTVShowBaslikLabel3 = new javax.swing.JLabel();
        eslesenFilmYokLabel1 = new javax.swing.JLabel();
        eslesenDiziYokLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NETFLIX");
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        kullaniciBilgileriPanel.setBackground(new java.awt.Color(55, 55, 55));
        kullaniciBilgileriPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true));
        kullaniciBilgileriPanel.setMinimumSize(new java.awt.Dimension(200, 250));
        kullaniciBilgileriPanel.setPreferredSize(new java.awt.Dimension(200, 250));

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("emailLabel");
        emailLabel.setToolTipText("");

        cikisYapButton.setBackground(new java.awt.Color(55, 55, 55));
        cikisYapButton.setForeground(new java.awt.Color(255, 255, 255));
        cikisYapButton.setText("Çıkış Yap");
        cikisYapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisYapButtonActionPerformed(evt);
            }
        });

        kullaniciIsimLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kullaniciIsimLabel.setForeground(new java.awt.Color(255, 255, 255));
        kullaniciIsimLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kullaniciIsimLabel.setText("jLabel1");
        kullaniciIsimLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        jButton2.setBackground(new java.awt.Color(55, 55, 55));
        jButton2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<--");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kullaniciBilgileriPanelLayout = new javax.swing.GroupLayout(kullaniciBilgileriPanel);
        kullaniciBilgileriPanel.setLayout(kullaniciBilgileriPanelLayout);
        kullaniciBilgileriPanelLayout.setHorizontalGroup(
            kullaniciBilgileriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciBilgileriPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kullaniciBilgileriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kullaniciBilgileriPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(kullaniciIsimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullaniciBilgileriPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cikisYapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        kullaniciBilgileriPanelLayout.setVerticalGroup(
            kullaniciBilgileriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciBilgileriPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kullaniciIsimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cikisYapButton)
                .addGap(22, 22, 22))
        );

        getContentPane().add(kullaniciBilgileriPanel);
        kullaniciBilgileriPanel.setBounds(1050, 50, 200, 250);

        anaEkranBaslikPanel.setBackground(new java.awt.Color(23, 23, 23));
        anaEkranBaslikPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        anaEkranBaslikPanel.setLayout(null);

        turAramaButton.setBackground(new java.awt.Color(23, 23, 23));
        turAramaButton.setForeground(new java.awt.Color(255, 255, 255));
        turAramaButton.setText("türe göre arama yap");
        turAramaButton.setBorderPainted(false);
        turAramaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turAramaButtonActionPerformed(evt);
            }
        });
        anaEkranBaslikPanel.add(turAramaButton);
        turAramaButton.setBounds(240, 10, 140, 30);

        aramaTextField.setText("İsme göre Arama yap ");
        aramaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aramaTextFieldMouseClicked(evt);
            }
        });
        anaEkranBaslikPanel.add(aramaTextField);
        aramaTextField.setBounds(770, 10, 260, 30);

        araButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filmResimleri/arama.jpg"))); // NOI18N
        araButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        araButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araButtonActionPerformed(evt);
            }
        });
        anaEkranBaslikPanel.add(araButton);
        araButton.setBounds(1030, 10, 30, 30);

        anaEkranaDonButton.setBackground(new java.awt.Color(23, 23, 23));
        anaEkranaDonButton.setForeground(new java.awt.Color(255, 255, 255));
        anaEkranaDonButton.setText("Ana Ekran");
        anaEkranaDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anaEkranaDonButtonActionPerformed(evt);
            }
        });
        anaEkranBaslikPanel.add(anaEkranaDonButton);
        anaEkranaDonButton.setBounds(380, 10, 90, 30);

        kullaniciBilgileriButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filmResimleri/kisi.png"))); // NOI18N
        kullaniciBilgileriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciBilgileriButtonActionPerformed(evt);
            }
        });
        anaEkranBaslikPanel.add(kullaniciBilgileriButton);
        kullaniciBilgileriButton.setBounds(1140, 0, 50, 50);

        jButton1.setBackground(new java.awt.Color(23, 23, 23));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("İsme gore arama sonuc Paneli");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        anaEkranBaslikPanel.add(jButton1);
        jButton1.setBounds(470, 10, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filmResimleri/baslikLogo.png"))); // NOI18N
        anaEkranBaslikPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 90, 47);

        jButton3.setBackground(new java.awt.Color(23, 23, 23));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Tüm programlar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        anaEkranBaslikPanel.add(jButton3);
        jButton3.setBounds(120, 10, 120, 30);

        getContentPane().add(anaEkranBaslikPanel);
        anaEkranBaslikPanel.setBounds(0, 0, 1280, 50);

        anaEkranPanel.setBackground(new java.awt.Color(33, 33, 33));
        anaEkranPanel.setAutoscrolls(true);
        anaEkranPanel.setInheritsPopupMenu(true);
        anaEkranPanel.setMinimumSize(new java.awt.Dimension(1280, 710));
        anaEkranPanel.setPreferredSize(new java.awt.Dimension(1280, 710));
        anaEkranPanel.setLayout(null);

        izlemeyeDevamEtLabel.setBackground(new java.awt.Color(55, 55, 55));
        izlemeyeDevamEtLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        izlemeyeDevamEtLabel.setForeground(new java.awt.Color(255, 255, 255));
        izlemeyeDevamEtLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        izlemeyeDevamEtLabel.setText("jLabel1");
        izlemeyeDevamEtLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        anaEkranPanel.add(izlemeyeDevamEtLabel);
        izlemeyeDevamEtLabel.setBounds(260, 20, 720, 40);

        anaEkranScrollPane.setViewportView(anaEkranPanel);

        getContentPane().add(anaEkranScrollPane);
        anaEkranScrollPane.setBounds(0, 47, 1280, 660);

        ismeGoreAramaSonucScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        ismeGoreAramaSonucScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        ismeGoreAramaSonucScrollPane.setAutoscrolls(true);
        ismeGoreAramaSonucScrollPane.setPreferredSize(new java.awt.Dimension(1230, 650));

        ismeGoreAramaSonucPanel.setBackground(new java.awt.Color(33, 33, 33));
        ismeGoreAramaSonucPanel.setAutoscrolls(true);
        ismeGoreAramaSonucPanel.setPreferredSize(new java.awt.Dimension(1350, 329));

        filmlerBaslikLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        filmlerBaslikLabel.setForeground(new java.awt.Color(255, 255, 255));
        filmlerBaslikLabel.setText("Filmler Katagorisinde Bulunan Sonuçlar");

        dizilerVeTVShowBaslikLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dizilerVeTVShowBaslikLabel2.setForeground(new java.awt.Color(255, 255, 255));
        dizilerVeTVShowBaslikLabel2.setText("Dizi ve Tv Show Katagorisinde Bulunan Sonuçlar :");

        eslesenFilmYokLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        eslesenFilmYokLabel.setForeground(new java.awt.Color(255, 255, 255));
        eslesenFilmYokLabel.setText("Eşleşen bir film bulunamadı");

        eslesenDiziYokLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        eslesenDiziYokLabel.setForeground(new java.awt.Color(255, 255, 255));
        eslesenDiziYokLabel.setText("Eşleşen bir dizi veya tv show bulunamadı");

        javax.swing.GroupLayout ismeGoreAramaSonucPanelLayout = new javax.swing.GroupLayout(ismeGoreAramaSonucPanel);
        ismeGoreAramaSonucPanel.setLayout(ismeGoreAramaSonucPanelLayout);
        ismeGoreAramaSonucPanelLayout.setHorizontalGroup(
            ismeGoreAramaSonucPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ismeGoreAramaSonucPanelLayout.createSequentialGroup()
                .addGroup(ismeGoreAramaSonucPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ismeGoreAramaSonucPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filmlerBaslikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ismeGoreAramaSonucPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(eslesenDiziYokLabel))
                    .addGroup(ismeGoreAramaSonucPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(eslesenFilmYokLabel))
                    .addGroup(ismeGoreAramaSonucPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dizilerVeTVShowBaslikLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(641, Short.MAX_VALUE))
        );
        ismeGoreAramaSonucPanelLayout.setVerticalGroup(
            ismeGoreAramaSonucPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ismeGoreAramaSonucPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filmlerBaslikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(eslesenFilmYokLabel)
                .addGap(191, 191, 191)
                .addComponent(dizilerVeTVShowBaslikLabel2)
                .addGap(49, 49, 49)
                .addComponent(eslesenDiziYokLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ismeGoreAramaSonucScrollPane.setViewportView(ismeGoreAramaSonucPanel);

        getContentPane().add(ismeGoreAramaSonucScrollPane);
        ismeGoreAramaSonucScrollPane.setBounds(0, 46, 1270, 620);

        tureGoreAramaSonucScrollPane.setPreferredSize(new java.awt.Dimension(1230, 610));

        tureGoreAramaPanel.setBackground(new java.awt.Color(33, 33, 33));
        tureGoreAramaPanel.setMinimumSize(new java.awt.Dimension(1254, 683));
        tureGoreAramaPanel.setLayout(null);

        sonucYokLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        sonucYokLabel.setForeground(new java.awt.Color(255, 255, 255));
        sonucYokLabel.setText("Eşleşen bir dizi veya tv show bulunamadı");
        sonucYokLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        tureGoreAramaPanel.add(sonucYokLabel);
        sonucYokLabel.setBounds(340, 138, 654, 46);

        kategoriSecLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kategoriSecLabel.setForeground(new java.awt.Color(255, 255, 255));
        kategoriSecLabel.setText("Kategori Seç :");
        tureGoreAramaPanel.add(kategoriSecLabel);
        kategoriSecLabel.setBounds(60, 10, 96, 18);

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Aksiyon ve Macera");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        tureGoreAramaPanel.add(jCheckBox1);
        jCheckBox1.setBounds(60, 30, 209, 23);

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Bilim Kurgu ve Fantastik Yapımlar");
        tureGoreAramaPanel.add(jCheckBox2);
        jCheckBox2.setBounds(60, 60, 209, 23);

        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Belgesel");
        tureGoreAramaPanel.add(jCheckBox3);
        jCheckBox3.setBounds(60, 87, 210, 23);

        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Komedi");
        tureGoreAramaPanel.add(jCheckBox4);
        jCheckBox4.setBounds(60, 110, 210, 23);

        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Bilim ve Doğa");
        tureGoreAramaPanel.add(jCheckBox5);
        jCheckBox5.setBounds(60, 130, 210, 23);

        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText(" Çocuk ve Aile");
        tureGoreAramaPanel.add(jCheckBox6);
        jCheckBox6.setBounds(60, 150, 210, 23);

        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("Korku");
        tureGoreAramaPanel.add(jCheckBox7);
        jCheckBox7.setBounds(60, 172, 210, 23);

        jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setText("Gerilim");
        tureGoreAramaPanel.add(jCheckBox8);
        jCheckBox8.setBounds(60, 200, 210, 23);

        jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setText("Reality Program");
        tureGoreAramaPanel.add(jCheckBox9);
        jCheckBox9.setBounds(60, 230, 210, 23);

        jCheckBox10.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox10.setText("Anime");
        tureGoreAramaPanel.add(jCheckBox10);
        jCheckBox10.setBounds(60, 340, 210, 23);

        jCheckBox11.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setText("Romantik");
        tureGoreAramaPanel.add(jCheckBox11);
        jCheckBox11.setBounds(60, 260, 210, 23);

        jCheckBox12.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox12.setText("Aksiyon");
        tureGoreAramaPanel.add(jCheckBox12);
        jCheckBox12.setBounds(60, 320, 210, 23);

        jCheckBox13.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox13.setText("Drama");
        tureGoreAramaPanel.add(jCheckBox13);
        jCheckBox13.setBounds(60, 290, 210, 23);
        tureGoreAramaPanel.add(tureGoreAramaTextField);
        tureGoreAramaTextField.setBounds(340, 10, 540, 37);

        tureGoreAraButton.setText("Türe göre ara");
        tureGoreAraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tureGoreAraButtonActionPerformed(evt);
            }
        });
        tureGoreAramaPanel.add(tureGoreAraButton);
        tureGoreAraButton.setBounds(880, 10, 120, 40);

        bulunanDiziFilmlerLabel.setFont(new java.awt.Font("Alef", 1, 24)); // NOI18N
        bulunanDiziFilmlerLabel.setForeground(new java.awt.Color(255, 255, 255));
        bulunanDiziFilmlerLabel.setText("Bulunan dizi ve filmler:");
        tureGoreAramaPanel.add(bulunanDiziFilmlerLabel);
        bulunanDiziFilmlerLabel.setBounds(500, 60, 280, 34);

        tureGoreAramaSonucScrollPane.setViewportView(tureGoreAramaPanel);

        getContentPane().add(tureGoreAramaSonucScrollPane);
        tureGoreAramaSonucScrollPane.setBounds(0, 46, 1270, 660);

        programIzlemePanel.setBackground(new java.awt.Color(51, 51, 51));
        programIzlemePanel.setMinimumSize(new java.awt.Dimension(1280, 710));
        programIzlemePanel.setPreferredSize(new java.awt.Dimension(1280, 710));
        programIzlemePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                programIzlemePanelMouseMoved(evt);
            }
        });
        programIzlemePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        izlenenDakikaLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        izlenenDakikaLabel.setForeground(new java.awt.Color(255, 255, 255));
        izlenenDakikaLabel.setText("DAKİKA");
        programIzlemePanel.add(izlenenDakikaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 299, 108));

        programIzlemeGeriButton.setBackground(new java.awt.Color(51, 51, 51));
        programIzlemeGeriButton.setForeground(new java.awt.Color(255, 255, 255));
        programIzlemeGeriButton.setText("<-- Geri");
        programIzlemeGeriButton.setOpaque(false);
        programIzlemeGeriButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                programIzlemeGeriButtonMouseEntered(evt);
            }
        });
        programIzlemeGeriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programIzlemeGeriButtonActionPerformed(evt);
            }
        });
        programIzlemePanel.add(programIzlemeGeriButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 34, -1, -1));
        programIzlemePanel.add(ilerGeriSarSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 580, 950, -1));

        programBasligiLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        programBasligiLabel.setForeground(new java.awt.Color(255, 255, 255));
        programBasligiLabel.setText("İsim ve bölüm bilgisi");
        programIzlemePanel.add(programBasligiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 30, 720, 40));

        programSuresiLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        programSuresiLabel.setForeground(new java.awt.Color(255, 255, 255));
        programSuresiLabel.setText("jLabel4");
        programIzlemePanel.add(programSuresiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1141, 587, -1, -1));

        programIzlemeDurdurmaButton.setBackground(new java.awt.Color(51, 51, 51));
        programIzlemeDurdurmaButton.setForeground(new java.awt.Color(255, 255, 255));
        programIzlemeDurdurmaButton.setText("Play/Pause");
        programIzlemePanel.add(programIzlemeDurdurmaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 581, -1, -1));

        puanVerButton.setBackground(new java.awt.Color(51, 51, 51));
        puanVerButton.setForeground(new java.awt.Color(255, 255, 255));
        puanVerButton.setText("Puan Ver");
        puanVerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                puanVerButtonMouseEntered(evt);
            }
        });
        puanVerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puanVerButtonActionPerformed(evt);
            }
        });
        programIzlemePanel.add(puanVerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1126, 30, 100, -1));

        oncekiBolumButton.setBackground(new java.awt.Color(51, 51, 51));
        oncekiBolumButton.setForeground(new java.awt.Color(255, 255, 255));
        oncekiBolumButton.setText("<-- Öncekii Bölüm");
        oncekiBolumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oncekiBolumButtonActionPerformed(evt);
            }
        });
        programIzlemePanel.add(oncekiBolumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 299, -1, -1));

        sonrakiBolumButton2.setBackground(new java.awt.Color(51, 51, 51));
        sonrakiBolumButton2.setForeground(new java.awt.Color(255, 255, 255));
        sonrakiBolumButton2.setText("Sonraki Bölüm -->");
        sonrakiBolumButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonrakiBolumButton2ActionPerformed(evt);
            }
        });
        programIzlemePanel.add(sonrakiBolumButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 300, -1, -1));

        getContentPane().add(programIzlemePanel);
        programIzlemePanel.setBounds(0, 0, 1280, 710);

        tumProgramlarScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        tumProgramlarScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        tumProgramlarScrollPane.setAutoscrolls(true);
        tumProgramlarScrollPane.setPreferredSize(new java.awt.Dimension(1230, 650));

        tumProgramlarSonucPanel.setBackground(new java.awt.Color(33, 33, 33));
        tumProgramlarSonucPanel.setAutoscrolls(true);
        tumProgramlarSonucPanel.setPreferredSize(new java.awt.Dimension(1350, 329));

        filmlerBaslikLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        filmlerBaslikLabel1.setForeground(new java.awt.Color(255, 255, 255));
        filmlerBaslikLabel1.setText("Filmler Katagorisindeki Programlar :");

        dizilerVeTVShowBaslikLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dizilerVeTVShowBaslikLabel3.setForeground(new java.awt.Color(255, 255, 255));
        dizilerVeTVShowBaslikLabel3.setText("Dizi ve Tv Show Katagorisindeki Programlar :");

        eslesenFilmYokLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        eslesenFilmYokLabel1.setForeground(new java.awt.Color(255, 255, 255));
        eslesenFilmYokLabel1.setText("Eşleşen bir film bulunamadı");

        eslesenDiziYokLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        eslesenDiziYokLabel1.setForeground(new java.awt.Color(255, 255, 255));
        eslesenDiziYokLabel1.setText("Eşleşen bir dizi veya tv show bulunamadı");

        javax.swing.GroupLayout tumProgramlarSonucPanelLayout = new javax.swing.GroupLayout(tumProgramlarSonucPanel);
        tumProgramlarSonucPanel.setLayout(tumProgramlarSonucPanelLayout);
        tumProgramlarSonucPanelLayout.setHorizontalGroup(
            tumProgramlarSonucPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tumProgramlarSonucPanelLayout.createSequentialGroup()
                .addGroup(tumProgramlarSonucPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tumProgramlarSonucPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filmlerBaslikLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tumProgramlarSonucPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(eslesenDiziYokLabel1))
                    .addGroup(tumProgramlarSonucPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(eslesenFilmYokLabel1))
                    .addGroup(tumProgramlarSonucPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dizilerVeTVShowBaslikLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(641, Short.MAX_VALUE))
        );
        tumProgramlarSonucPanelLayout.setVerticalGroup(
            tumProgramlarSonucPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tumProgramlarSonucPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filmlerBaslikLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(eslesenFilmYokLabel1)
                .addGap(191, 191, 191)
                .addComponent(dizilerVeTVShowBaslikLabel3)
                .addGap(49, 49, 49)
                .addComponent(eslesenDiziYokLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tumProgramlarScrollPane.setViewportView(tumProgramlarSonucPanel);

        getContentPane().add(tumProgramlarScrollPane);
        tumProgramlarScrollPane.setBounds(0, 46, 1270, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void araButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araButtonActionPerformed
        //aramaislemleri yapilacak

        String filmIsim = aramaTextField.getText();
        if (!filmIsim.trim().equals("")) {
            ismeGoreAramaYap(filmIsim);
            ismeGoreAramaPaneliGorunurYap();
        }

    }//GEN-LAST:event_araButtonActionPerformed

    private void turAramaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turAramaButtonActionPerformed
        tureGoreAramaPanaliniGorunurYap();
    }//GEN-LAST:event_turAramaButtonActionPerformed

    private void aramaTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aramaTextFieldMouseClicked
        aramaTextField.setText(""); // içeriği null yapiliyor.
    }//GEN-LAST:event_aramaTextFieldMouseClicked

    private void tureGoreAraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tureGoreAraButtonActionPerformed
        turIsimleriArrayList.clear();// isimler arayi sifirlaniyor.

        String programIsmi = tureGoreAramaTextField.getText();
        if (!programIsmi.trim().equals("")) {

            for (JCheckBox checkBox : turCheckBoxs) {
                if (checkBox.isSelected()) {
                    turIsimleriArrayList.add(checkBox.getText());
                }
            }
            int x = 300, y = 100;
            if (turIsimleriArrayList.isEmpty()) {
                bilgiMesajı.mesajVer("Lütfen bir tür seçiniz", "Tur Seçilmedi");
            } else {
                tureGoreAramaYap(programIsmi, turIsimleriArrayList, x, y, 180);
            }
        }


    }//GEN-LAST:event_tureGoreAraButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void programIzlemeGeriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programIzlemeGeriButtonActionPerformed
        sayacThread.stop();
        if (verilenPuan == 0) {
            bilgiMesajı.mesajVer("ilk önce puan vermelisiniz", "PUAN");
            puanVerFrameniAktifEt();

        } else {
            this.izledigimSure = metinOlarakVerilenSureyiDakikayaDonustur(izlenenDakikaLabel.getText());
            izlenmeBilgileriniVeriTabaninaEkle(gloabalProgramID, izledigimSure, kalinanBolum, verilenPuan);
            anaPaneliGorunurYap();
            kullanicininIzledigiFilmeleriAnaPaneleEkle();
            kalinanBolum = 1;
        }

        //puanla
    }//GEN-LAST:event_programIzlemeGeriButtonActionPerformed

    private void anaEkranaDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anaEkranaDonButtonActionPerformed
        anaPaneliGorunurYap();
        kullanicininIzledigiFilmeleriAnaPaneleEkle();
    }//GEN-LAST:event_anaEkranaDonButtonActionPerformed

    private void kullaniciBilgileriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciBilgileriButtonActionPerformed
        kullaniciBilgileriPanel.setVisible(true);
    }//GEN-LAST:event_kullaniciBilgileriButtonActionPerformed

    private void programIzlemePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programIzlemePanelMouseMoved
        // bu fonksiyon kaybolan izleme bari ve geriye donme sekmesini geri getirir.
        programBasligiLabel.setVisible(true);
        programIzlemeGeriButton.setVisible(true);
        programIzlemeDurdurmaButton.setVisible(true);
        programSuresiLabel.setVisible(true);
        ilerGeriSarSlider.setVisible(true);
        puanVerButton.setVisible(true);
        oncekiBolumButton.setVisible(true);
        sonrakiBolumButton2.setVisible(true);
        try {
            Thread.sleep(10);
            repaint();
        } catch (InterruptedException ex) {
            System.out.println("Thread kesintiye ugradi");
        }
    }//GEN-LAST:event_programIzlemePanelMouseMoved

    private void puanVerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puanVerButtonMouseEntered
        puanVerButton.setVisible(true);
    }//GEN-LAST:event_puanVerButtonMouseEntered

    private void programIzlemeGeriButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programIzlemeGeriButtonMouseEntered

        programIzlemeGeriButton.setVisible(true);

    }//GEN-LAST:event_programIzlemeGeriButtonMouseEntered

    private void puanVerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puanVerButtonActionPerformed
        puanVerFrameniAktifEt();


    }//GEN-LAST:event_puanVerButtonActionPerformed

    private void sonrakiBolumButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonrakiBolumButton2ActionPerformed
        if (kalinanBolum > 0 && kalinanBolum < programinBolumSayisi) {
            sayacThread.stop(); // sayac durduruluyor.
            kalinanBolum++;
            String kalinanBolumLocal = Integer.toString(kalinanBolum);
            programIzlemePaneliniAktiflestir(programAdi, kalinanBolumLocal,
                    programinUzunlugu, programinTipi,
                    Integer.toString(gloabalProgramID),
                    Integer.toString(programinBolumSayisi), "0");
        }

    }//GEN-LAST:event_sonrakiBolumButton2ActionPerformed

    private void oncekiBolumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oncekiBolumButtonActionPerformed

        if (kalinanBolum >= 2) {
            sayacThread.stop(); // sayac durduruluyor.
            kalinanBolum--; // suanki bolum bir eksiltiliyor.
            String kalinanBolumLocal = Integer.toString(kalinanBolum);
            programIzlemePaneliniAktiflestir(programAdi, kalinanBolumLocal,
                    programinUzunlugu, programinTipi,
                    Integer.toString(gloabalProgramID),
                    Integer.toString(programinBolumSayisi), "0");
        }
    }//GEN-LAST:event_oncekiBolumButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        kullaniciBilgileriPanel.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cikisYapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisYapButtonActionPerformed
        OturumKontolcusu.cikisYap();
        GirisGUI.gorunurOl();// giris ekrani baslatiliyor
        dispose();

    }//GEN-LAST:event_cikisYapButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ismeGoreAramaSonucPanel.setVisible(true);
        ismeGoreAramaSonucScrollPane.setVisible(true);
        anaEkranPanel.setVisible(false);
        anaEkranScrollPane.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tumProgramlarSonucPaneliniGorunurYap();
    }//GEN-LAST:event_jButton3ActionPerformed
    private void pencereyiOrtala() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
    }

    private void ismeGoreAramaPaneliGorunurYap() {
        anaEkranPanel.setVisible(false);
        tureGoreAramaPanel.setVisible(false);
        tureGoreAramaSonucScrollPane.setVisible(false);
        ismeGoreAramaSonucPanel.setVisible(true);
        ismeGoreAramaSonucScrollPane.setVisible(true);
        anaEkranScrollPane.setVisible(false);
        tumProgramlarScrollPane.setVisible(false);
        tumProgramlarSonucPanel.setVisible(false);
        repaint();

    }

    private void tumProgramlarSonucPaneliniGorunurYap() {
        anaEkranPanel.setVisible(false);
        tureGoreAramaPanel.setVisible(false);
        tureGoreAramaSonucScrollPane.setVisible(false);
        ismeGoreAramaSonucPanel.setVisible(false);
        ismeGoreAramaSonucScrollPane.setVisible(false);
        anaEkranScrollPane.setVisible(false);
        tumProgramlarScrollPane.setVisible(true);
        tumProgramlarSonucPanel.setVisible(true);
        repaint();

    }

    private void puanVerFrameniAktifEt() {
        PuanlamaFrame puanlamaFrame = new PuanlamaFrame();
        JButton button = puanlamaFrame.getjButton1();
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                puanlamaFrame.puaniDon();
                verilenPuan = puanlamaFrame.puan;
                puanlamaFrame.yokOl();
            }
        });

    }

    private void paneleProgramEkle(JPanel anaJpanel, String programID, String ad,
            String uzunluk, String bolumSayisi, String tip, String kalinanBolum,
            String kalinanSure, int x, int y) {

        String path = "/filmResimleri/" + programID + ".jpg";
        String playButtonPath = "/filmResimleri/playButton.jpg";
        //System.out.println(path);
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        ImageIcon playIcon = new ImageIcon(getClass().getResource(playButtonPath));

        JButton button = new JButton(icon);
        JButton playButton = new JButton(playIcon);
        // playButton.setText("İZLE");
        Color color = new Color(255, 0, 0);
        Border borderRed = BorderFactory.createLineBorder(color, 3);
        Border borderWhite = BorderFactory.createLineBorder(new Color(255, 255, 255), 3);
        button.setBorder(borderWhite);

        playButton.setOpaque(false);

        playButton.setBorder(null);
        playButton.setBorderPainted(false);
        playButton.setContentAreaFilled(false);
        JLabel label = new JLabel();
        JLabel kalinanBolumLabel = new JLabel();
        label.setText(ad);
        kalinanBolumLabel.setText(kalinanBolum + ".Bölum");
        label.setForeground(Color.white);
        kalinanBolumLabel.setForeground(Color.white);

        label.setBounds(x, y + 200, 140, 20);
        kalinanBolumLabel.setBounds(x, y + 215, 140, 20);
        button.setBounds(x, y, 140, 190);
        playButton.setBounds(30, 50, 50, 70);
        anaJpanel.add(button);
        button.add(playButton);
        playButton.setVisible(false);
        anaJpanel.add(label);
        if (!kalinanSure.equals("0")) {
            anaJpanel.add(kalinanBolumLabel);
        }
        repaint();
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playButton.setVisible(true);
                button.setBorder(borderRed);
                try {
                    Thread.sleep(75);

                    repaint();
                } catch (InterruptedException ex) {
                    System.out.println("Thread kesintiye ugradi");
                }
                repaint();
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                playButton.setVisible(false);
                button.setBorder(borderWhite);
                try {
                    Thread.sleep(75);

                    repaint();
                } catch (InterruptedException ex) {
                    System.out.println("Thread kesintiye ugradi");
                }
                repaint();
            }
        });
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playButton.setVisible(true);
                button.setBorder(borderRed);
                try {
                    Thread.sleep(50);

                    repaint();
                } catch (InterruptedException ex) {
                    System.out.println("Thread kesintiye ugradi");
                }
                repaint();
            }

        });
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playButton.setVisible(false);
                button.setBorder(borderWhite);
                try {
                    Thread.sleep(50);

                    repaint();
                } catch (InterruptedException ex) {
                    System.out.println("Thread kesintiye ugradi");
                }
                repaint();
            }

        });
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //System.out.println(programID);
                /*
                programIzlemePaneliniKur(ad, kalinanBolum, uzunluk);
                int sure = Integer.parseInt(uzunluk);
                programIzlemePaneliniGorunurYap();
                programdakiSureyiBaslat(sure);
                programAdi = ad;
                programinTipi = tip;
                gloabalProgramID = Integer.parseInt(programID);
                programinBolumSayisi=Integer.parseInt(bolumSayisi);
                 */
                verilenPuan = 0; // puan sıfırlanıyor. 

                programIzlemePaneliniAktiflestir(ad, kalinanBolum, uzunluk, tip,
                        programID, bolumSayisi, kalinanSure);
            }
        });

        //button.seti
    }

    private void programIzlemePaneliniAktiflestir(String ad, String kalinanBolum,
            String uzunluk, String tip, String programID, String bolumSayisi, String baslangisSuresi) {
        programIzlemePaneliniKur(ad, kalinanBolum, uzunluk);
        int sure = Integer.parseInt(uzunluk);
        int baslangicSuresiInt = Integer.parseInt(baslangisSuresi);
        programIzlemePaneliniGorunurYap();
        programdakiSureyiBaslat(sure, baslangicSuresiInt);
        programAdi = ad;
        programinTipi = tip;
        gloabalProgramID = Integer.parseInt(programID);
        programinBolumSayisi = Integer.parseInt(bolumSayisi);
        programinUzunlugu = uzunluk;
    }

    private void ismeGoreAramaYap(String programIsmi) {

        ismeGoreAramaYapPaneliTemizle();
        ArrayList<ArrayList<String>> filmler;
        filmler = veriTabanı.ismeGoreFilmAra(programIsmi);
        ArrayList<ArrayList<String>> dizilerVeTVShowlari;
        dizilerVeTVShowlari = veriTabanı.ismeGoreDiziveTVShowAra(programIsmi);
        // ArrayList<String> program = new ArrayList<>();

        int filmlerx = 50, filmlery = 45;
        int dizilerx = 50, dizilery = 330;
        int xKoordinatiArtisMiktari = 180;
        if (filmler.isEmpty()) {
            eslesenFilmYokLabel.setVisible(true);
        }
        if (dizilerVeTVShowlari.isEmpty()) {
            eslesenDiziYokLabel.setVisible(true);
        }

        programListesindekiProgramlariPaneleEkle(filmler, ismeGoreAramaSonucPanel,
                filmlerx, filmlery, xKoordinatiArtisMiktari);
        programListesindekiProgramlariPaneleEkle(dizilerVeTVShowlari, ismeGoreAramaSonucPanel,
                dizilerx, dizilery, xKoordinatiArtisMiktari);
        repaint();
    }

    private void tumProgramlariPaneleEkle(String programIsmi) {

        tumProgramlarPaneliniTemizle();
        ArrayList<ArrayList<String>> filmler;
        filmler = veriTabanı.ismeGoreFilmAra(programIsmi);
        ArrayList<ArrayList<String>> dizilerVeTVShowlari;
        dizilerVeTVShowlari = veriTabanı.ismeGoreDiziveTVShowAra(programIsmi);
        // ArrayList<String> program = new ArrayList<>();

        int filmlerx = 50, filmlery = 45;
        int dizilerx = 50, dizilery = 330;
        int xKoordinatiArtisMiktari = 180;
        if (filmler.isEmpty()) {
            eslesenFilmYokLabel1.setVisible(true);
        }
        if (dizilerVeTVShowlari.isEmpty()) {
            eslesenDiziYokLabel1.setVisible(true);
        }

        programListesindekiProgramlariPaneleEkle(filmler, tumProgramlarSonucPanel,
                filmlerx, filmlery, xKoordinatiArtisMiktari);
        programListesindekiProgramlariPaneleEkle(dizilerVeTVShowlari, tumProgramlarSonucPanel,
                dizilerx, dizilery, xKoordinatiArtisMiktari);
        repaint();
    }

    private void tureGoreAramaYap(String programIsmi, ArrayList<String> turIsimleri,
            Integer x, Integer y, int xKoordinatiArtisMiktari) {
        tureGoreAramaYapPaneliniTemizle();
        ArrayList<ArrayList<String>> programlar;
        String id;
        String uzunluk;
        String bolumSayisi;
        String tip;
        String ad;
        int toplamBoyut = 0;
        for (String turIsmi : turIsimleri) {
            programlar = veriTabanı.tureGoreAramaYap(programIsmi, turIsmi);
            toplamBoyut += programlar.size();
            for (ArrayList<String> program : programlar) {

                id = program.get(0);
                ad = program.get(1);
                uzunluk = program.get(2);
                bolumSayisi = program.get(3);
                tip = program.get(4);
                paneleProgramEkle(tureGoreAramaPanel, id, ad, uzunluk, bolumSayisi, tip, "1", "0", x, y);
                x += xKoordinatiArtisMiktari;

                if (x + 200 > tureGoreAramaPanel.getWidth()) {
                    x = 300;
                    y += 250;
                    //panelinBoyutunuArttir(tureGoreAramaPanel, tureGoreAramaPanel.getWidth(), tureGoreAramaPanel.getHeight());

                }
                if (y > tureGoreAramaPanel.getHeight()) {
                    panelinBoyutunuArttir(tureGoreAramaPanel, tureGoreAramaPanel.getWidth(), y + 260);
                }
            }
        }
        if (toplamBoyut == 0) {

            sonucYokLabel.setVisible(true);
        } else {
            sonucYokLabel.setVisible(false);
        }

    }

    private void programListesindekiProgramlariPaneleEkle(
            ArrayList<ArrayList<String>> programlar, JPanel panel, int x, int y,
            int xKoordinatiArtisMiktari) {

        for (ArrayList<String> program : programlar) {
            String id;
            String uzunluk;
            String bolumSayisi;
            String tip;
            String ad;
            id = program.get(0);
            ad = program.get(1);
            uzunluk = program.get(2);
            bolumSayisi = program.get(3);
            tip = program.get(4);
            paneleProgramEkle(panel, id, ad, uzunluk, bolumSayisi, tip, "1", "0", x, y);
            x += xKoordinatiArtisMiktari;

            if (x > panel.getWidth()) {
                panelinBoyutunuArttir(panel, x, panel.getHeight());

            }
        }

    }

    private void kullanicininIzledigiFilmeleriAnaPaneleEkle() {
        anaPaneliTemizle();
        ArrayList<ArrayList<String>> izlenenProgramlar;
        izlenenProgramlar = veriTabanı.kullanicininIzlemisOlduguProgramlarinIdsiniGetir(id);
        ArrayList<String> programinOzellikleriArrayList;
        int x = 60, y = 90;
        int xKoordinatiArtisMiktari = 200;
        for (ArrayList<String> program : izlenenProgramlar) {
            String id = program.get(0);
            String sure = program.get(1);
            String kalinanBolum = program.get(2);
            programinOzellikleriArrayList = veriTabanı.idyeGoreProgramOzellikleriniGetir(id);
            if (!programinOzellikleriArrayList.isEmpty()) {
                String ad = programinOzellikleriArrayList.get(0);
                String uzunluk = programinOzellikleriArrayList.get(1);
                String bolumSayisi = programinOzellikleriArrayList.get(2);
                String tip = programinOzellikleriArrayList.get(3);
                paneleProgramEkle(anaEkranPanel, id, ad, uzunluk, bolumSayisi, tip, kalinanBolum, sure, x, y);
                x += xKoordinatiArtisMiktari;

                if (x + 200 > anaEkranPanel.getWidth()) {
                    x = 60;
                    y += 275;
                    //panelinBoyutunuArttir(tureGoreAramaPanel, tureGoreAramaPanel.getWidth(), tureGoreAramaPanel.getHeight());

                }
                if (y + 300 > anaEkranPanel.getHeight()) {
                    panelinBoyutunuArttir(anaEkranPanel, anaEkranPanel.getWidth(), anaEkranPanel.getHeight() + 400);
                }
            }

        }
        repaint();
    }

    private void anaPaneliTemizle() {
        anaEkranPanel.removeAll();
        izlemeyeDevamEtLabel.setText(adSoyad + " izlemeye kaldığın yerden devam et");
        anaEkranPanel.add(izlemeyeDevamEtLabel);
        panelinBoyutunuArttir(ismeGoreAramaSonucPanel, 500, 900);
    }

    private void ismeGoreAramaYapPaneliTemizle() {
        ismeGoreAramaSonucPanel.removeAll();
        //filmlerBulunanSonuclarPanel.setSize(filmlerBulunanSonuclarPanel.getWidth(), 900);
        panelinBoyutunuArttir(ismeGoreAramaSonucPanel, 500, 600);
        ismeGoreAramaSonucPanel.add(filmlerBaslikLabel);
        ismeGoreAramaSonucPanel.add(dizilerVeTVShowBaslikLabel2);
        ismeGoreAramaSonucPanel.add(eslesenDiziYokLabel);
        ismeGoreAramaSonucPanel.add(eslesenFilmYokLabel);
        programIzlemePanel.setVisible(false);
        eslesenDiziYokLabel.setVisible(false);
        eslesenFilmYokLabel.setVisible(false);
        repaint();

    }

    private void tumProgramlarPaneliniTemizle() {
        tumProgramlarSonucPanel.removeAll();
        panelinBoyutunuArttir(tumProgramlarSonucPanel, 500, 600);

        tumProgramlarSonucPanel.add(filmlerBaslikLabel1);
        tumProgramlarSonucPanel.add(dizilerVeTVShowBaslikLabel3);
        tumProgramlarSonucPanel.add(eslesenDiziYokLabel1);
        tumProgramlarSonucPanel.add(eslesenFilmYokLabel1);
        programIzlemePanel.setVisible(false);
        eslesenDiziYokLabel1.setVisible(false);
        eslesenFilmYokLabel1.setVisible(false);
        repaint();
    }

    private void tureGoreAramaYapPaneliniTemizle() {
        tureGoreAramaPanel.removeAll();
        panelinBoyutunuArttir(tureGoreAramaPanel, 1300, 800);
        for (JCheckBox checkBox : turCheckBoxs) { // checkboxlar eklendi.
            tureGoreAramaPanel.add(checkBox);
        }
        tureGoreAramaPanel.add(tureGoreAraButton);
        tureGoreAramaPanel.add(kategoriSecLabel);
        tureGoreAramaPanel.add(tureGoreAramaTextField);
        tureGoreAramaPanel.add(bulunanDiziFilmlerLabel);
        tureGoreAramaPanel.add(sonucYokLabel);
        sonucYokLabel.setVisible(false);
        repaint();
    }

    public void panelinBoyutunuArttir(JPanel panel, int w, int h) {

        Dimension dimension = new Dimension(w, h);
        panel.setPreferredSize(dimension);
        panel.setSize(dimension);
    }

    private void tureGoreAramaPanaliniGorunurYap() {
        anaEkranPanel.setVisible(false);
        anaEkranScrollPane.setVisible(false);
        tureGoreAramaPanel.setVisible(true);
        tureGoreAramaSonucScrollPane.setVisible(true);
        ismeGoreAramaSonucPanel.setVisible(false);
        programIzlemePanel.setVisible(false);
        //aramaTextField.setVisible(false);
        //araButton.setVisible(false);
        ismeGoreAramaSonucScrollPane.setVisible(false);
        sonucYokLabel.setVisible(false);
        tumProgramlarScrollPane.setVisible(false);
        tumProgramlarSonucPanel.setVisible(false);
        repaint();

    }

    private void anaPaneliGorunurYap() {
        anaEkranPanel.setVisible(true);
        anaEkranScrollPane.setVisible(true);
        tureGoreAramaPanel.setVisible(false);
        tureGoreAramaSonucScrollPane.setVisible(false);
        ismeGoreAramaSonucPanel.setVisible(false);
        programIzlemePanel.setVisible(false);
        anaEkranBaslikPanel.setVisible(true);
        araButton.setVisible(true);
        aramaTextField.setVisible(true);
        ismeGoreAramaSonucScrollPane.setVisible(false);
        kullaniciBilgileriPanel.setVisible(false);
        kullaniciIsimLabel.setText(adSoyad);
        emailLabel.setText(email);
        tumProgramlarScrollPane.setVisible(false);
        tumProgramlarSonucPanel.setVisible(false);

    }

    private void izlenmeBilgileriniVeriTabaninaEkle(int programID, int izlenenSure,
            int kalinanBolum, int verilenPuan) {
        // giris yaparken aldigimiz kullanici idsi donusturuluyor.
        int kullaniciID = Integer.parseInt(this.id);
        Calendar calendar = Calendar.getInstance();
        Date date = calendar.getTime();
        SimpleDateFormat format1 = new SimpleDateFormat("dd-MM-yyyy");

        String tarih = format1.format(date);
        tarih = tarih.replace('-', '/');
        //System.out.println(tarih);
        veriTabanı.kullaniciProgramTablosunaVeriEkle(programID, kullaniciID, tarih,
                izlenenSure, kalinanBolum, verilenPuan);

    }

    private void programIzlemePaneliniGorunurYap() {
        anaEkranPanel.setVisible(false);
        anaEkranScrollPane.setVisible(false);
        tureGoreAramaPanel.setVisible(false);
        tureGoreAramaSonucScrollPane.setVisible(false);
        ismeGoreAramaSonucPanel.setVisible(false);
        ismeGoreAramaSonucScrollPane.setVisible(false);
        anaEkranBaslikPanel.setVisible(false);
        programIzlemePanel.setVisible(true);
        tumProgramlarScrollPane.setVisible(false);
        tumProgramlarSonucPanel.setVisible(false);
        kullaniciBilgileriPanel.setVisible(false);

        repaint();

    }

    private void programIzlemePaneliniKur(String programIsmi, String bolumSayisi, String sure) {
        // bu fonksiyon program basligi gibi bilgileri ve kullaniciyla etkilesimi saglayan fonksiyonlari aktif eder.
        String baslik = programIsmi + ":" + bolumSayisi + ".bölüm";
        programBasligiLabel.setText(baslik);
        int sureInt = Integer.parseInt(sure) * 60;
        sure = sureyiFormatla(sureInt); // sure formatlandi.
        programSuresiLabel.setText(sure);
        repaint();
    }

    private String sureyiFormatla(int sureInt) {
        // bu fonksiyon saniye cinsindeki sureyi saat:dakika:saniye olarak formatlar.
        String donusturulenSure = "";
        int dakika, saniye, saat;
        saat = sureInt / 3600;
        sureInt -= (saat * 3600);
        dakika = sureInt / 60;
        sureInt -= (dakika * 60);
        saniye = sureInt;
        //System.out.println(sure);
        //System.out.println(saat + " " + dakika +" "+ saniye);
        String saatStr = saat > 9 ? Integer.toString(saat) : "0" + Integer.toString(saat);
        String dakikaStr = dakika > 9 ? Integer.toString(dakika) : "0" + Integer.toString(dakika);
        String saniyeStr = saniye > 9 ? Integer.toString(saniye) : "0" + Integer.toString(saniye);
        donusturulenSure = saatStr + ":" + dakikaStr + ":" + saniyeStr;
        return donusturulenSure;
    }

    private void programdakiSureyiBaslat(int sure, int baslangicSuresi) {
        //sure saniye cinsinden.
        //programIzle tusuna basinca geri sayimi baslatan fonksiyon
        sayacThread = new Thread(new Runnable() {
            @Override
            public void run() {

                String text;
                int beklemeSuresi = 0;
                for (int i = baslangicSuresi; i < sure * 60; i++) {
                    text = sureyiFormatla(i);
                    izlenenDakikaLabel.setText(text);
                    //System.out.println(text);
                    if (beklemeSuresi > 10) {

                        programBasligiLabel.setVisible(false);
                        programIzlemeGeriButton.setVisible(false);
                        programIzlemeDurdurmaButton.setVisible(false);
                        programSuresiLabel.setVisible(false);
                        ilerGeriSarSlider.setVisible(false);
                        puanVerButton.setVisible(false);
                        oncekiBolumButton.setVisible(false);
                        sonrakiBolumButton2.setVisible(false);
                        beklemeSuresi = 0;
                    }
                    try {

                        Thread.sleep(1000);// 1 saniye uyuluyor.
                    } catch (InterruptedException ex) {
                        System.out.println("thread kesintiye uğradı" + ex);
                    }
                    beklemeSuresi++;
                }
            }
        });
        sayacThread.start(); // thread baslatiliyor.*/

    }

    private int metinOlarakVerilenSureyiDakikayaDonustur(String text) {
        int sonuc = 0;
        String parcalanmis[] = text.split(":");
        int saat = Integer.parseInt(parcalanmis[0]);
        int dakika = Integer.parseInt(parcalanmis[1]);
        int saniye = Integer.parseInt(parcalanmis[2]);

        sonuc = (saat * 3600) + (dakika * 60) + saniye;

        return sonuc;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anaEkranBaslikPanel;
    private javax.swing.JPanel anaEkranPanel;
    private javax.swing.JScrollPane anaEkranScrollPane;
    private javax.swing.JButton anaEkranaDonButton;
    private javax.swing.JButton araButton;
    private javax.swing.JTextField aramaTextField;
    private javax.swing.JLabel bulunanDiziFilmlerLabel;
    private javax.swing.JButton cikisYapButton;
    private javax.swing.JLabel dizilerVeTVShowBaslikLabel2;
    private javax.swing.JLabel dizilerVeTVShowBaslikLabel3;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel eslesenDiziYokLabel;
    private javax.swing.JLabel eslesenDiziYokLabel1;
    private javax.swing.JLabel eslesenFilmYokLabel;
    private javax.swing.JLabel eslesenFilmYokLabel1;
    private javax.swing.JLabel filmlerBaslikLabel;
    private javax.swing.JLabel filmlerBaslikLabel1;
    private javax.swing.JSlider ilerGeriSarSlider;
    private javax.swing.JPanel ismeGoreAramaSonucPanel;
    private javax.swing.JScrollPane ismeGoreAramaSonucScrollPane;
    private javax.swing.JLabel izlemeyeDevamEtLabel;
    private javax.swing.JLabel izlenenDakikaLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kategoriSecLabel;
    private javax.swing.JButton kullaniciBilgileriButton;
    private javax.swing.JPanel kullaniciBilgileriPanel;
    private javax.swing.JLabel kullaniciIsimLabel;
    private javax.swing.JButton oncekiBolumButton;
    private javax.swing.JLabel programBasligiLabel;
    private javax.swing.JButton programIzlemeDurdurmaButton;
    private javax.swing.JButton programIzlemeGeriButton;
    private javax.swing.JPanel programIzlemePanel;
    private javax.swing.JLabel programSuresiLabel;
    private javax.swing.JButton puanVerButton;
    private javax.swing.JButton sonrakiBolumButton2;
    private javax.swing.JLabel sonucYokLabel;
    private javax.swing.JScrollPane tumProgramlarScrollPane;
    private javax.swing.JPanel tumProgramlarSonucPanel;
    private javax.swing.JButton turAramaButton;
    private javax.swing.JButton tureGoreAraButton;
    private javax.swing.JPanel tureGoreAramaPanel;
    private javax.swing.JScrollPane tureGoreAramaSonucScrollPane;
    private javax.swing.JTextField tureGoreAramaTextField;
    // End of variables declaration//GEN-END:variables
}
